"""Write src/builtin_data.h: the speakers built into EchoVRMusic.dll.

Usage: python tools/gen_builtin.py

- BUILTIN_MAPS: every maps/<level>.txt in this project (placed in game with the dev build, or
  exported from Blender with blender/echovrmusic_speakers.py). A map's speakers replace the music
  speakers Echo itself uses on that level, so this covers flat-music levels like the arena too.
- BUILTIN_SETTINGS: default settings (none needed today; the plugin's defaults are in Settings).
Then run setup/build_setup.bat (or tools/make_release.py).
"""
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")


def raw(text):
    return 'R"EVM(' + text + ')EVM"'


def main():
    settings = ""
    maps = []
    mdir = os.path.join(ROOT, "maps")
    for fn in sorted(os.listdir(mdir)):
        if fn.lower().endswith(".txt"):
            text = open(os.path.join(mdir, fn), encoding="utf-8-sig").read()
            maps.append((fn[:-4], text))
    out = [
        "// Generated by tools/gen_builtin.py from maps/*.txt -- don't edit, rerun the script.",
        "#pragma once",
        "",
        "static const char* const BUILTIN_SETTINGS = " + raw(settings) + ";",
        "",
        "struct BuiltinMap { const char* level; const char* text; };",
        "static const BuiltinMap BUILTIN_MAPS[] = {",
    ]
    for level, text in maps:
        out.append('    {"%s", %s},' % (level, raw(text)))
    out.append("};")
    path = os.path.join(ROOT, "src", "builtin_data.h")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s: %d map(s): %s" % (path, len(maps), ", ".join(m[0] for m in maps)))


if __name__ == "__main__":
    main()
