"""Write src/builtin_data.h: the speakers built into EchoVRMusic.dll.

Usage: python tools/gen_builtin.py

- BUILTIN_SETTINGS: default settings plus the arena's speakers (Speaker@<music event> lines).
- BUILTIN_MAPS: every maps/<level>.txt in this project (exported from Blender with
  blender/echovrmusic_speakers.py).
Then run setup/build_setup.bat.
"""
import os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")

# mpl_arena_a plays its music flat (music event 0x4edefef9): Echo Speaker System's 18 arena
# speakers, each moved 7.5 m in toward the middle (the originals sat too far out), lower ring 10 m
# up, upper ring 35 m up (Echo coordinates, z runs goal to goal).
ARENA = [
    (28.7, 10, 18), (27.5, 10, 0), (28.7, 10, -18), (23.2, 10, -39.5), (-23.2, 10, -39.5),
    (-28.7, 10, -18), (-27.5, 10, 0), (-28.7, 10, 18), (-23.2, 10, 39.5), (23.2, 10, 39.5),
    (-24.9, 35, 26.5), (-26.9, 35, 8.7), (-26.9, 35, -8.7), (-24.9, 35, -26.5), (24.9, 35, -26.5),
    (26.9, 35, -8.7), (26.9, 35, 8.7), (24.9, 35, 26.5),
]


def raw(text):
    return 'R"EVM(' + text + ')EVM"'


def main():
    settings = "\n".join("Speaker@0x4edefef9 = %g %g %g" % p for p in ARENA) + "\n"
    maps = []
    mdir = os.path.join(ROOT, "maps")
    for fn in sorted(os.listdir(mdir)):
        if fn.lower().endswith(".txt"):
            text = open(os.path.join(mdir, fn), encoding="utf-8-sig").read()
            maps.append((fn[:-4], text))
    out = [
        "// Generated by tools/gen_builtin.py from maps/*.txt -- don't edit, rerun the script.",
        "#pragma once",
        "",
        "static const char* const BUILTIN_SETTINGS = " + raw(settings) + ";",
        "",
        "struct BuiltinMap { const char* level; const char* text; };",
        "static const BuiltinMap BUILTIN_MAPS[] = {",
    ]
    for level, text in maps:
        out.append('    {"%s", %s},' % (level, raw(text)))
    out.append("};")
    path = os.path.join(ROOT, "src", "builtin_data.h")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print("wrote %s: %d map(s): %s" % (path, len(maps), ", ".join(m[0] for m in maps)))


if __name__ == "__main__":
    main()
