// Generated by tools/gen_builtin.py from maps/*.txt -- don't edit, rerun the script.
#pragma once

static const char* const BUILTIN_SETTINGS = R"EVM(Speaker@0x4edefef9 = 28.7 10 18
Speaker@0x4edefef9 = 27.5 10 0
Speaker@0x4edefef9 = 28.7 10 -18
Speaker@0x4edefef9 = 23.2 10 -39.5
Speaker@0x4edefef9 = -23.2 10 -39.5
Speaker@0x4edefef9 = -28.7 10 -18
Speaker@0x4edefef9 = -27.5 10 0
Speaker@0x4edefef9 = -28.7 10 18
Speaker@0x4edefef9 = -23.2 10 39.5
Speaker@0x4edefef9 = 23.2 10 39.5
Speaker@0x4edefef9 = -24.9 35 26.5
Speaker@0x4edefef9 = -26.9 35 8.7
Speaker@0x4edefef9 = -26.9 35 -8.7
Speaker@0x4edefef9 = -24.9 35 -26.5
Speaker@0x4edefef9 = 24.9 35 -26.5
Speaker@0x4edefef9 = 26.9 35 -8.7
Speaker@0x4edefef9 = 26.9 35 8.7
Speaker@0x4edefef9 = 24.9 35 26.5
)EVM";

struct BuiltinMap { const char* level; const char* text; };
static const BuiltinMap BUILTIN_MAPS[] = {
    {"mpl_combat_combustion", R"EVM(# EchoVRMusic speakers for mpl_combat_combustion, placed in game with key 1 (your head position)
# Echo coordinates in metres: x, y (up), z
Level = mpl_combat_combustion
LevelId = 0x42670f2bed45703c
Speaker = -200.254 -7.920 -199.952
Speaker = -21.220 2.377 81.940
Speaker = -30.516 2.388 81.618
Speaker = -6.805 6.258 35.442
Speaker = -46.387 4.626 38.313
Speaker = -34.498 6.592 9.001
Speaker = -34.624 6.592 -8.730
Speaker = -45.479 5.089 -38.245
Speaker = -5.884 6.534 -47.423
Speaker = -20.264 5.662 -18.984
Speaker = -5.847 7.193 0.131
Speaker = 15.539 2.130 -11.658
Speaker = 16.597 2.308 10.354
Speaker = -10.112 5.626 28.147
Speaker = 2.724 4.302 -28.026
Speaker = 150.327 -7.916 199.864
Speaker = -25.735 1.245 -82.541
Speaker = -30.430 2.248 -81.708
Speaker = -20.814 2.399 -81.442
)EVM"},
    {"mpl_combat_dyson", R"EVM(# EchoVRMusic speakers for mpl_combat_dyson, placed in game with key 1 (your head position)
# Echo coordinates in metres: x, y (up), z
Level = mpl_combat_dyson
LevelId = 0x43e2da7914642604
Speaker = -200.399 -8.344 -199.901
Speaker = -100.447 17.155 -0.095
Speaker = -29.176 0.569 0.032
Speaker = -8.940 1.374 5.084
Speaker = -7.147 6.312 -16.760
Speaker = -0.051 8.490 -30.816
Speaker = -35.479 -1.190 -35.491
Speaker = 7.645 6.533 -16.479
Speaker = 8.992 1.521 5.201
Speaker = 0.020 3.127 13.616
Speaker = 150.248 -8.474 199.996
Speaker = 99.838 17.108 0.040
Speaker = 28.810 0.617 0.056
Speaker = 36.066 -0.061 36.333
Speaker = 35.451 -0.919 -35.418
Speaker = -0.004 22.245 11.656
Speaker = -36.103 -0.007 36.054
)EVM"},
    {"mpl_combat_fission", R"EVM(# EchoVRMusic speakers for mpl_combat_fission, placed in game with key 1 (your head position)
# Echo coordinates in metres: x, y (up), z
Level = mpl_combat_fission
LevelId = 0xdf5ca7b7dfa383d4
Speaker = -200.251 -7.907 -200.055
Speaker = -55.673 -9.159 29.949
Speaker = -15.541 -7.548 0.071
Speaker = -8.015 -7.563 -0.034
Speaker = 22.836 0.875 7.575
Speaker = 9.935 0.949 -13.343
Speaker = 46.832 0.179 -4.196
Speaker = 37.294 -3.786 -18.619
Speaker = 35.654 -3.885 12.341
Speaker = 61.835 0.813 -3.768
Speaker = 150.538 -7.904 199.903
Speaker = 72.045 -2.593 -3.984
Speaker = -54.668 -3.842 -11.183
Speaker = -54.249 0.856 10.511
Speaker = -62.952 -2.220 -21.250
Speaker = -71.764 0.870 12.262
Speaker = -82.238 -1.167 0.084
Speaker = -99.557 0.055 -5.279
Speaker = -98.042 1.218 6.562
Speaker = -104.743 -10.254 0.079
Speaker = -14.324 -8.964 19.020
Speaker = -124.572 -5.318 -0.073
Speaker = -109.058 -5.267 14.189
Speaker = -109.136 -5.288 -14.255
)EVM"},
    {"mpl_combat_gauss", R"EVM(# EchoVRMusic speakers for mpl_combat_gauss (Surge), placed in game with key 1 (your head position)
# Echo coordinates in metres: x, y (up), z
Level = mpl_combat_gauss
LevelId = 0x43e2da7a0c623a19
Speaker = -200.306 -8.763 -199.855
Speaker = -39.923 1.904 33.345
Speaker = -17.295 5.330 -7.351
Speaker = 20.684 4.848 -3.885
Speaker = 21.629 4.726 -3.019
Speaker = 33.682 2.575 20.963
Speaker = 44.622 2.618 8.356
Speaker = -17.377 5.270 -7.263
Speaker = 150.141 -8.644 200.007
Speaker = 52.468 3.035 27.827
Speaker = -48.886 13.635 0.490
Speaker = -28.728 13.612 29.063
Speaker = -37.035 11.929 60.929
Speaker = -61.839 17.591 37.347
Speaker = -73.160 13.376 15.550
Speaker = -76.137 13.555 12.757
Speaker = -95.635 16.809 20.243
Speaker = -95.693 16.768 20.251
Speaker = -95.679 16.777 5.594
Speaker = -95.690 16.779 5.575
Speaker = -119.580 18.356 3.887
Speaker = -124.917 18.385 21.099
Speaker = -112.855 18.158 14.298
Speaker = -127.627 18.319 7.447
Speaker = -132.124 14.568 12.608
Speaker = -146.596 13.606 12.592
)EVM"},
};
